# Generated by Django 2.2.19 on 2021-03-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_accountstatus_user_name'),
        ('profiles', '0015_auto_20180423_0727'),
    ]

    operations = [
    ]
